driver:
  name: ec2
  instance_type: m3.medium
  aws_ssh_key_id: serdar
  region: us-west-2

provisioner:
  name: chef_zero

transport:
  ssh_key: /Users/serdar/.ssh/serdar_aws.pem

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-7f675e4f
  - name: windows-2012r2
    driver:
      security_group_ids: ["sg-46dd6a23"]
      instance_type: m3.large
      image_id: ami-83a5bce2
      user_data: |
        <powershell>
        $logfile="C:\\Program Files\\Amazon\\Ec2ConfigService\\Logs\\kitchen-ec2.log"
        #PS Remoting and & winrm.cmd basic config
        Enable-PSRemoting -Force -SkipNetworkProfileCheck
        & winrm.cmd set winrm/config '@{MaxTimeoutms="1800000"}' >> $logfile
        & winrm.cmd set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}' >> $logfile
        & winrm.cmd set winrm/config/winrs '@{MaxShellsPerUser="50"}' >> $logfile
        #Server settings - support username/password login
        & winrm.cmd set winrm/config/service/auth '@{Basic="true"}' >> $logfile
        & winrm.cmd set winrm/config/service '@{AllowUnencrypted="true"}' >> $logfile
        & winrm.cmd set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}' >> $logfile
        #Firewall Config
        & netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" profile=public protocol=tcp localport=5985 remoteip=localsubnet new remoteip=any  >> $logfile
        #Set script execution to unrestricted
        & Set-ExecutionPolicy Unrestricted -Force
        </powershell>


suites:
  - name: gem_versions
    provisioner:
      product_name: chef
      product_version: latest
      channel: current
    run_list:
